import type { CompiledField, CompiledFormTool } from "./types.js";

export type PandaScriptOptions = {
  pageUrl: string;
  tool: CompiledFormTool;
  values?: Record<string, unknown>;
  autoSubmit?: boolean;
};

function jsString(value: string): string {
  return JSON.stringify(value);
}

function formScope(formIndex: number): string {
  if (formIndex === 0) return "form";
  return `form:nth-of-type(${formIndex + 1})`;
}

function scoped(formIndex: number, selector: string): string {
  if (formIndex === 0) return selector;
  return `${formScope(formIndex)} ${selector}`;
}

function fieldSelector(formIndex: number, field: CompiledField, radioValue?: string): string {
  if (field.kind === "enum" && field.widget === "select") {
    return scoped(formIndex, `select[name=${jsString(field.name)}]`);
  }
  if (field.kind === "enum" && radioValue !== undefined) {
    return scoped(
      formIndex,
      `input[type="radio"][name=${jsString(field.name)}][value=${jsString(radioValue)}]`,
    );
  }
  if (field.kind === "boolean") {
    return scoped(formIndex, `input[type="checkbox"][name=${jsString(field.name)}]`);
  }
  if (field.kind === "checkboxes" && radioValue !== undefined) {
    return scoped(
      formIndex,
      `input[type="checkbox"][name=${jsString(field.name)}][value=${jsString(radioValue)}]`,
    );
  }
  if (field.kind === "text" && field.inputType === "textarea") {
    return scoped(formIndex, `textarea[name=${jsString(field.name)}]`);
  }
  return scoped(formIndex, `input[name=${jsString(field.name)}]`);
}

function submitSelector(formIndex: number): string {
  if (formIndex === 0) return "button";
  return scoped(formIndex, `button:not([type="button"])`);
}

function valueForField(field: CompiledField, values: Record<string, unknown>): unknown {
  return values[field.name];
}

function literalForScript(raw: unknown, fieldName: string): string {
  if (raw === undefined || raw === null) {
    return `"" /* ${fieldName} */`;
  }
  if (typeof raw === "string" && raw.startsWith("$LP_")) {
    return jsString(raw);
  }
  if (Array.isArray(raw)) {
    return jsString(raw.join(","));
  }
  return jsString(String(raw));
}

function shouldEmitField(field: CompiledField, raw: unknown): boolean {
  if (field.kind === "checkboxes") {
    return raw !== undefined && raw !== null && (Array.isArray(raw) ? raw.length > 0 : true);
  }
  if (raw === undefined || raw === null || raw === "") {
    return field.required;
  }
  return true;
}

export function generatePandaScript(opts: PandaScriptOptions): string {
  const { pageUrl, tool, values = {}, autoSubmit = false } = opts;
  const lines: string[] = [
    `// ${tool.description}`,
    `// Generated by mint-webmcp — replay: lightpanda run script.js`,
    `// Tool: ${tool.toolName}`,
    "",
    "const page = new Page();",
    `await page.goto(${jsString(pageUrl)});`,
    'page.waitForState("networkidle");',
    "",
  ];

  for (const field of tool.fields) {
    const raw = valueForField(field, values);
    if (!shouldEmitField(field, raw)) continue;

    if (field.kind === "enum") {
      const chosen = raw !== undefined && raw !== null ? String(raw) : field.values[0] ?? "";
      if (field.widget === "select") {
        lines.push(`page.selectOption(${jsString(fieldSelector(tool.formIndex, field))}, ${literalForScript(chosen, field.name)});`);
      } else {
        lines.push(`page.setChecked(${jsString(fieldSelector(tool.formIndex, field, chosen))}, true);`);
      }
      continue;
    }
    if (field.kind === "boolean") {
      const on = raw === true || raw === "true" || raw === 1 || raw === "1";
      lines.push(`page.setChecked(${jsString(fieldSelector(tool.formIndex, field))}, ${on ? "true" : "false"});`);
      continue;
    }
    if (field.kind === "checkboxes") {
      const selected = Array.isArray(raw) ? raw.map(String) : [String(raw)];
      for (const opt of field.values) {
        const on = selected.includes(opt);
        lines.push(`page.setChecked(${jsString(fieldSelector(tool.formIndex, field, opt))}, ${on ? "true" : "false"});`);
      }
      continue;
    }
    lines.push(`page.fill(${jsString(fieldSelector(tool.formIndex, field))}, ${literalForScript(raw, field.name)});`);
  }

  if (autoSubmit) {
    lines.push("");
    lines.push("// Submit");
    lines.push(`page.click(${jsString(submitSelector(tool.formIndex))});`);
    lines.push('page.waitForState("networkidle");');
    lines.push('return page.evaluate("document.body ? document.body.innerText : \\"\\"");');
  } else {
    lines.push("");
    lines.push(`// page.click(${jsString(submitSelector(tool.formIndex))});`);
    lines.push('return { status: "filled" };');
  }

  return lines.join("\n");
}
